#  Data Preparation Exercise 

แบบฝึกหัดนี้เป็นแบบฝึกหัดทดสอบทักษะการเตรียมข้อมูล โดยให้ทำตามคำสั่ง ต่อไปนี้

---

**Import pandas and numpy**

In [1]:
import pandas as pd
import numpy as np

**1. ให้นำข้อมูลจาก Salaries.csv มาตรวจสอบว่าใครบ้างที่ทำงานเป็นตำรวจ แล้วสร้างไฟล์ .csv เก็บข้อมูลไว้**

In [22]:
sal = pd.read_csv('Salaries.csv')
Police_job = sal[sal['JobTitle'].apply (lambda x : 'POLICE' in x.upper())]
Police_job.to_csv('Police_Data.csv' , index = False)
PoD = pd.read_csv('Police_Data.csv')
PoD

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
2,12,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.00,87082.62,110804.30,NaN,297608.92,297608.92,2011,NaN,San Francisco,NaN
3,16,RICHARD CORRIEA,"COMMANDER III, (POLICE DEPARTMENT)",198778.01,73478.20,13957.65,NaN,286213.86,286213.86,2011,NaN,San Francisco,NaN
4,26,GREGORY SUHR,CHIEF OF POLICE,256470.41,0.00,11522.18,NaN,267992.59,267992.59,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8196,148313,Jerome J Alamil,Police Officer,309.90,0.00,0.00,64.52,309.90,374.42,2014,NaN,San Francisco,NaN
8197,148410,Dennis V Cravalho,Police Officer,0.00,0.00,242.66,0.00,242.66,242.66,2014,NaN,San Francisco,NaN
8198,148438,Elizabeth A Maron,Police Officer 3,0.00,0.00,212.39,0.00,212.39,212.39,2014,NaN,San Francisco,NaN
8199,148507,Patricia O Williams,Community Police Services Aide,0.00,0.00,134.78,0.00,134.78,134.78,2014,NaN,San Francisco,NaN
8200,148562,Marshall Robles,Community Police Services Aide,0.00,0.00,59.59,10.78,59.59,70.37,2014,NaN,San Francisco,NaN

**2. ให้นำข้อมูลจาก sale_quarterly1.xlsx มาสร้าง Pivot Table เพื่อแสดง ยอดขายเฉลี่ยของพนักงานในแต่ละควอเตอร์**

In [40]:
sq = pd.read_excel('sale_quarterly1.xlsx', usecols = 'b:e',header = 2 )
sq.pivot_table(index = 'Employee' , 
               columns= 'Quarter' ,
               values = 'Sales' , 
               aggfunc = 'mean' , 
               fill_value = 0)

Quarter          1       2       3       4
Employee
Bill         800.0    60.0   300.0    50.0
Maria        500.0    50.0   200.0   750.0
Tina         400.0   700.0   750.0   250.0
กอบเกียรติ   300.0   500.0   900.0   900.0
ณิแนน       1000.0  1000.0  1000.0  1000.0

In [43]:
sq.pivot_table(index = 'Quarter' , 
               values = 'Sales' , 
               aggfunc = 'mean' , 
               fill_value = 0 )

         Sales
Quarter
1        600.0
2        462.0
3        630.0
4        590.0

**3. ให้นำข้อมูลจาก data_clean_bfclean.csv คอลัมน์ SQ_M มาจัดการ**

โดยที่
- ข้อมูลที่มีค่าน้อยกว่า 100 ถือว่าเป็นข้อมูลที่ผิดพลาด ให้เปลี่ยนเป็น Null
- ข้อมูลที่ไม่ใช่ตัวเลขถือเป็นข้อมูลที่ผิดพลาด ให้เปลี่ยนเป็น Null
- ทำคอลัมน์ให้เป็น float64

In [32]:
dcb = pd.read_csv('data_clean_bfclean.csv')
dcb

      PID  ST_NUM  ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_M
0     กอบ   104.0   PUTNAM            Y           3.0        1   1000
1     แนน   197.0    LETON            n           3.0        1     --
2     Lam     NaN    LETON            N           NaN        1    850
3   Ninan   201.0    BEREY            N           1.0       -2  700.5
4     Nii     NaN    BEREY            Y           2.0     2ABC   1600
5     Tom   207.0    BEREY            Y           3.0      1.5  800.8
6   Green     NaN   WAGTON          NaN           2.0        3    950
7   Shasa   213.0  TREMONT            Y           1.0        1    NaN
8   Alisa   215.0  TREMONT            Y           2.0        2   1800
9     Ksb   216.0  TREMONT            n           2.0        2   90.5
10    Jib   217.0  TREMONT           12           2.0        2   70.2

In [33]:
dcb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PID           11 non-null     object
 1   ST_NUM        8 non-null      float64
 2   ST_NAME       11 non-null     object
 3   OWN_OCCUPIED  10 non-null     object
 4   NUM_BEDROOMS  10 non-null     float64
 5   NUM_BATH      11 non-null     object
 6   SQ_M          10 non-null     object
dtypes: float64(2), object(5)
memory usage: 748.0+ bytes

In [34]:
def cln(x):
    try :
        val = float(x)
        if val < 100 :
            return np.nan
        else : 
            return val
    except : 
        return np.nan

In [36]:
dcb['SQ_M'] = dcb['SQ_M'].apply(cln)
dcb

      PID  ST_NUM  ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH    SQ_M
0     กอบ   104.0   PUTNAM            Y           3.0        1  1000.0
1     แนน   197.0    LETON            n           3.0        1     NaN
2     Lam     NaN    LETON            N           NaN        1   850.0
3   Ninan   201.0    BEREY            N           1.0       -2   700.5
4     Nii     NaN    BEREY            Y           2.0     2ABC  1600.0
5     Tom   207.0    BEREY            Y           3.0      1.5   800.8
6   Green     NaN   WAGTON          NaN           2.0        3   950.0
7   Shasa   213.0  TREMONT            Y           1.0        1     NaN
8   Alisa   215.0  TREMONT            Y           2.0        2  1800.0
9     Ksb   216.0  TREMONT            n           2.0        2     NaN
10    Jib   217.0  TREMONT           12           2.0        2     NaN

In [38]:
dcb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PID           11 non-null     object
 1   ST_NUM        8 non-null      float64
 2   ST_NAME       11 non-null     object
 3   OWN_OCCUPIED  10 non-null     object
 4   NUM_BEDROOMS  10 non-null     float64
 5   NUM_BATH      11 non-null     object
 6   SQ_M          7 non-null      float64
dtypes: float64(3), object(4)
memory usage: 748.0+ bytes